import 'zone.js';import '@angular/compiler';
import {Component} from '@angular/core';import {bootstrapApplication} from '@angular/platform-browser';import {CommonModule} from '@angular/common';import {FormsModule} from '@angular/forms';import './styles.css';
@Component({selector:'demo-app',standalone:true,imports:[CommonModule,FormsModule],template:`<main><p class="eyebrow">INDEPENDENT ASSESSMENT REFERENCE</p><h1>{{title}}</h1><p class="note">Synthetic learner records. Scoring is deterministic; feedback publication requires instructor review.</p><div class="grid"><section><h2>Assessment workflow</h2><form (ngSubmit)="send()"><label for="action">Action</label><select id="action" name="action" [(ngModel)]="action" (change)="choose()"><option *ngFor="let a of actions">{{a}}</option></select><label for="role">Local role</label><select id="role" name="role" [(ngModel)]="role"><option>learner</option><option>instructor</option></select><div *ngFor="let key of keys"><label [for]="'field-'+key">{{key}}</label><input [id]="'field-'+key" [name]="key" [(ngModel)]="fields[key]" required></div><button type="submit" [disabled]="busy">Run workflow</button></form><p role="status" aria-live="polite">{{status}}</p></section><section><h2>Review result and audit</h2><button (click)="inspect()">Refresh records</button><pre>{{output}}</pre></section></div><p class="note">Local fixture roles only. External cloud services and model APIs are not configured.</p></main>`})
class DemoApp {
 title='Assessment review';actions:string[]=[];config:any;action='';role='learner';fields:Record<string,string>={};keys:string[]=[];output='Choose a workflow';status='Loading project…';busy=false;
 constructor(){fetch('/api/config').then(r=>r.json()).then(c=>{this.config=c;this.title=c.title;this.actions=c.actions;this.action=c.actions[0];this.choose();this.status='Ready'}).catch(e=>this.status=e.message)}
 choose(){this.fields=Object.fromEntries(Object.entries(this.config.samples[this.action]||{}).map(([k,v])=>[k,Array.isArray(v)?JSON.stringify(v):String(v)]));this.keys=Object.keys(this.fields);this.role=['feedback','publish'].includes(this.action)?'instructor':'learner'}
 async send(){this.busy=true;try{const sample=this.config.samples[this.action];const payload=Object.fromEntries(Object.entries(this.fields).map(([k,v])=>[k,Array.isArray(sample[k])?JSON.parse(v):typeof sample[k]==='number'?Number(v):v]));const response=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer local-'+this.role},body:JSON.stringify({action:this.action,payload})});this.output=JSON.stringify(await response.json(),null,2);this.status='HTTP '+response.status}catch(e){this.status=(e as Error).message}finally{this.busy=false}}
 async inspect(){try{const r=await fetch('/api/state',{headers:{Authorization:'Bearer local-operator'}});this.output=JSON.stringify(await r.json(),null,2)}catch(e){this.status=(e as Error).message}}
}
bootstrapApplication(DemoApp);
